import { v4 as uuid } from 'uuid';

export const NavBarData = [
  {
    id: uuid(),
    Name: "Live Scores",
    Description: "Live Cricket Scores",
    Role: "User",
    hidden: false,
    href: "/",
    hasSubOptions: false,
  },
  {
    id: uuid(),
    Name: "Schedule",
    Description: "Cricket Schedule",
    Role: "User",
    hidden: false,
    href: "/about-me",
    hasSubOptions: false,
  },
  {
    id: uuid(),
    Name: "Archives",
    Description: "Cricket Scorecard Archives",
    Role: "User",
    hidden: false,
    href: "/game",
    hasSubOptions: false,
  },
  {
    id: uuid(),
    Name: "News",
    Description: "This is My Apps in this Website",
    Role: "Private",
    hidden: false,
    href: "/cricket-news",
    hasSubOptions: true,
    subOptions: [
      {
        id: uuid(),
        Name: "All Stories",
        Description: "Latest Cricket News",
        Role: "Private",
        hidden: false,
        href: "/cricket-news",
      },
      {
        id: uuid(),
        Name: "Cricbuzz Plus",
        Description: "Cricbuzz Plus Premium Articles",
        Role: "Private",
        hidden: false,
        href: "/cricket-news/editorial/cb-plus",
      },
      {
        id: uuid(),
        Name: "Latest News",
        Description: "Latest Cricket News",
        Role: "Private",
        hidden: false,
        href: "/cricket-news/latest-news",
      },
      {
        id: uuid(),
        Name: "Topics",
        Description: "Latest Cricket Topics",
        Role: "Private",
        hidden: false,
        href: "/cricket-news/info/",
      },
      {
        id: uuid(),
        Name: "Spotlight",
        Description: "Cricket Editorials and Specials",
        Role: "Private",
        hidden: false,
        href: "/cricket-news/editorial/spotlight",
      },
      {
        id: uuid(),
        Name: "Opinions",
        Description: "Latest Cricket Opinions & Editorials",
        Role: "Private",
        hidden: false,
        href: "/cricket-news/editorial/editorial-list",
      },
      {
        id: uuid(),
        Name: "Specials",
        Description: "Latest Cricket Specials",
        Role: "Private",
        hidden: false,
        href: "/cricket-news/editorial/specials",
      },
      {
        id: uuid(),
        Name: "Stats & Analysis",
        Description: "Latest Cricket Stats & Analysis",
        Role: "Private",
        hidden: false,
        href: "/cricket-news/editorial/stats-analysis",
      },
      {
        id: uuid(),
        Name: "Interviews",
        Description: "Latest Cricket Player Interviews",
        Role: "Private",
        hidden: false,
        href: "/cricket-news/editorial/interviews",
      },
      {
        id: uuid(),
        Name: "Live Blogs",
        Description: "Latest Cricket Match live blogs",
        Role: "Private",
        hidden: false,
        href: "/cricket-news/editorial/live-blogs",
      },
      {
        id: uuid(),
        Name: "Harsha Bhogle",
        Description: "Articles and Videos by Harsha Bhogle",
        Role: "Private",
        hidden: false,
        href: "/cricket-news/experts/harsha-bhogle/170",
      },
    ],
  },
  {
    id: uuid(),
    Name: "Series",
    Description: "This is Info about Series.",
    Role: "Admin",
    hidden: false,
    href: "/cricket-schedule/series",
    hasSubOptions: true,
    /*
    <a class="text-white" target="_self" href="/cricket-schedule/series" >Series</a><span class ="cb-caret-down"></span> 
        
        <nav class="cb-sub-navigation"> 
            <a class="cb-subnav-item" target="_self" href="/cricket-series/7233/australia-tour-of-india-2023" title="Australia tour of India, 2023">Australia tour of India, 2023</a> 
            <a class="cb-subnav-item" target="_self" href="/cricket-series/6732/icc-cricket-world-cup-2023" title="ICC Cricket World Cup 2023">ICC Cricket World Cup 2023</a> 
            <a class="cb-subnav-item" target="_self" href="/cricket-series/6694/new-zealand-tour-of-bangladesh-2023" title="New Zealand tour of Bangladesh, 2023">New Zealand tour of Bangladesh, 2023</a> 
            <a class="cb-subnav-item" target="_self" href="/cricket-series/6290/pakistan-tour-of-australia-2023-24" title="Pakistan tour of Australia, 2023-24">Pakistan tour of Australia, 2023-24</a> 
            <a class="cb-subnav-item" target="_self" href="/cricket-series/6228/england-tour-of-west-indies-2023" title="England tour of West Indies, 2023">England tour of West Indies, 2023</a> 
            <a class="cb-subnav-item" target="_self" href="/cricket-series/6822/big-bash-league-2023-24" title="Big Bash League 2023-24">Big Bash League 2023-24</a> 
            <a class="cb-subnav-item" target="_self" href="/cricket-series/7250/england-women-tour-of-india-2023" title="England Women tour of India, 2023">England Women tour of India, 2023</a> 
            <a class="cb-subnav-item" target="_self" href="/cricket-series/6850/womens-big-bash-league-2023" title="Womens Big Bash League 2023">Womens Big Bash League 2023</a> 
            <a class="cb-subnav-item" target="_self" href="/cricket-series/6722/vijay-hazare-trophy-2023" title="Vijay Hazare Trophy 2023">Vijay Hazare Trophy 2023</a> 
            <a class="cb-text-link cb-subnav-item" target="_self" href="/cricket-schedule/series">All Series »</a>
        </nav>
    */
    subOptions: [
      {
        id: uuid(),
        Name: "Australia tour of India, 2023",
        Description: "Australia tour of India, 2023",
        Role: "Private",
        hidden: false,
        href: "/cricket-series/7233/australia-tour-of-india-2023",
      },
      {
        id: uuid(),
        Name: "ICC Cricket World Cup ",
        Description: "ICC Cricket World Cup 2023",
        Role: "Private",
        hidden: false,
        href: "/cricket-series/6732/icc-cricket-world-cup-2023",
      },
      {
        id: uuid(),
        Name: "All Series »",
        Description: "All Series »",
        Role: "Private",
        hidden: false,
        href: "/cricket-schedule/series",
      }
    ],
  },
  {
    id: uuid(),
    Name: "Teams",
    Description: "Cricket Teams",
    Role: "Private",
    hidden: false,
    href: "/cricket-team",
    hasSubOptions: true,
    subOptions: [
      {
        id: uuid(),
        Name: "Game1",
        Description: "This is subOptions1 about this is Website",
        Role: "Private",
        hidden: false,
        href: "/game1",
        hasSubOptions: false,
      },
      {
        id: uuid(),
        Name: "subOptions21",
        Description: "This is subOptions2 about this is Website",
        Role: "Private",
        hidden: false,
        href: "#",
        hasSubOptions: true,
      },
      {
        id: uuid(),
        Name: "subOptions3",
        Description: "This is subOptions3 about this is Website",
        Role: "Private",
        hidden: false,
        href: "#",
        hasSubOptions: false,
      },
    ],
  },
  {
    id: uuid(),
    Name: "Videos",
    Description: "This is My Apps in this Website",
    Role: "Private",
    hidden: false,
    href: "/game",
    hasSubOptions: true,
    subOptions: [
      {
        id: uuid(),
        Name: "Game1",
        Description: "This is subOptions1 about this is Website",
        Role: "Private",
        hidden: false,
        href: "/game1",
        hasSubOptions: false,
      },
      {
        id: uuid(),
        Name: "subOptions21",
        Description: "This is subOptions2 about this is Website",
        Role: "Private",
        hidden: false,
        href: "#",
        hasSubOptions: true,
      },
      {
        id: uuid(),
        Name: "subOptions3",
        Description: "This is subOptions3 about this is Website",
        Role: "Private",
        hidden: false,
        href: "#",
        hasSubOptions: false,
      },
    ],
  },
  {
    id: uuid(),
    Name: "Rankings",
    Description: "This is My Apps in this Website",
    Role: "Private",
    hidden: false,
    href: "/game",
    hasSubOptions: true,
    subOptions: [
      {
        id: uuid(),
        Name: "Game1",
        Description: "This is subOptions1 about this is Website",
        Role: "Private",
        hidden: false,
        href: "/game1",
        hasSubOptions: false,
      },
      {
        id: uuid(),
        Name: "subOptions21",
        Description: "This is subOptions2 about this is Website",
        Role: "Private",
        hidden: false,
        href: "#",
        hasSubOptions: true,
      },
      {
        id: uuid(),
        Name: "subOptions3",
        Description: "This is subOptions3 about this is Website",
        Role: "Private",
        hidden: false,
        href: "#",
        hasSubOptions: false,
      },
    ],
  },
  {
    id: uuid(),
    Name: "More",
    Description: "This is My Apps in this Website",
    Role: "Private",
    hidden: false,
    href: "/game",
    hasSubOptions: true,
    subOptions: [
      {
        id: uuid(),
        Name: "Game1",
        Description: "This is subOptions1 about this is Website",
        Role: "Private",
        hidden: false,
        href: "/game1",
        hasSubOptions: false,
      },
      {
        id: uuid(),
        Name: "subOptions21",
        Description: "This is subOptions2 about this is Website",
        Role: "Private",
        hidden: false,
        href: "#",
        hasSubOptions: true,
      },
      {
        id: uuid(),
        Name: "subOptions3",
        Description: "This is subOptions3 about this is Website",
        Role: "Private",
        hidden: false,
        href: "#",
        hasSubOptions: false,
      },
    ],
  },
];